server_tokens off;

map ${DOLLAR}http_upgrade ${DOLLAR}connection_upgrade {
  default upgrade;
  '' close;
}

upstream frontend_upstream {
  server frontend:3000;
}

upstream prometheus_upstream {
  server prometheus:9090;
}

upstream grafana_upstream {
  server grafana:3000;
}

server {
  listen ${PORT} default_server;
  server_name ${SERVER_NAME};
  port_in_redirect off;

  location / {
    return 301 https://${DOLLAR}host${DOLLAR}request_uri;
  }

  include includes/location_common.conf;
}

server {
  listen ${SSL_PORT} ssl;
  server_name ${SERVER_NAME};
  port_in_redirect off;

  ssl_certificate ${SSL_CERT_FILE};
  ssl_certificate_key ${SSL_CERT_KEY_FILE};
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  ssl_dhparam /etc/ssl/certs/dhparam-${SSL_DH_BITS}.pem;
  ssl_protocols ${SSL_PROTOCOLS};
  ssl_ciphers ${SSL_CIPHERS};
  ssl_prefer_server_ciphers ${SSL_PREFER_CIPHERS};
  ssl_stapling ${SSL_OCSP_STAPLING};
  ssl_stapling_verify ${SSL_OCSP_STAPLING};
  ssl_verify_client ${SSL_VERIFY};
  ssl_verify_depth ${SSL_VERIFY_DEPTH};

  client_max_body_size 10m;

  location / {
    include includes/cors.conf;
    proxy_set_header Host ${DOLLAR}host;
    proxy_set_header Proxy "";
    proxy_set_header Upgrade ${DOLLAR}http_upgrade;
    proxy_set_header Connection ${DOLLAR}connection_upgrade;
    proxy_set_header X-REAL-IP ${DOLLAR}remote_addr;
    proxy_set_header X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Port ${DOLLAR}server_port;
    proxy_set_header X-Forwarded-Proto ${DOLLAR}scheme;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_connect_timeout 60s;
    proxy_read_timeout 36000s;
    proxy_redirect off;
    proxy_pass_header Authorization;
    proxy_pass http://frontend_upstream;
  }

  location = /grafana {
    return 301 /grafana/;
  }

  location /grafana/ {
    include includes/cors.conf;
    proxy_set_header Host ${DOLLAR}host;
    proxy_set_header Proxy "";
    proxy_set_header Upgrade ${DOLLAR}http_upgrade;
    proxy_set_header Connection ${DOLLAR}connection_upgrade;
    proxy_set_header X-REAL-IP ${DOLLAR}remote_addr;
    proxy_set_header X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Port ${DOLLAR}server_port;
    proxy_set_header X-Forwarded-Proto ${DOLLAR}scheme;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_connect_timeout 60s;
    proxy_read_timeout 36000s;
    proxy_redirect off;
    proxy_pass_header Authorization;
    proxy_set_header X-Forwarded-Prefix /grafana;
    proxy_ssl_server_name on;
    proxy_ssl_name grafana;
    proxy_ssl_trusted_certificate /etc/nginx/certs/internal-ca.crt;
    proxy_ssl_verify on;
    proxy_pass https://grafana_upstream;
  }

  location = /prometheus {
    return 301 /prometheus/;
  }

  location /prometheus/ {
    include includes/cors.conf;
    proxy_set_header Host ${DOLLAR}host;
    proxy_set_header Proxy "";
    proxy_set_header Upgrade ${DOLLAR}http_upgrade;
    proxy_set_header Connection ${DOLLAR}connection_upgrade;
    proxy_set_header X-REAL-IP ${DOLLAR}remote_addr;
    proxy_set_header X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Port ${DOLLAR}server_port;
    proxy_set_header X-Forwarded-Proto ${DOLLAR}scheme;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_connect_timeout 60s;
    proxy_read_timeout 36000s;
    proxy_redirect off;
    proxy_pass_header Authorization;
    proxy_set_header X-Forwarded-Prefix /prometheus;
    proxy_ssl_server_name on;
    proxy_ssl_name prometheus;
    proxy_ssl_trusted_certificate /etc/nginx/certs/internal-ca.crt;
    proxy_ssl_verify on;
    proxy_pass https://prometheus_upstream;
  }

  include includes/location_common.conf;
}
