services:
  auth-service:
    image: trancendance-auth-service:latest
    build:
      context: .
      dockerfile: backend/services/auth_service/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - AUTH_SUPABASE_URL=${AUTH_SUPABASE_URL}
      - AUTH_SUPABASE_ANON_KEY=${AUTH_SUPABASE_ANON_KEY}
      - DATABASE_URL=${SUPABASE_DB_URL}

  chat-service:
    image: trancendance-chat-service:latest
    build:
      context: .
      dockerfile: backend/services/chat_service/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=${SUPABASE_DB_URL}

  org-service:
    image: trancendance-org-service:latest
    build:
      context: .
      dockerfile: backend/services/org_service/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=${SUPABASE_DB_URL}

  frontend:
    image: trancendance-frontend:latest
    profiles:
      - prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - chat-service
      - org-service
    env_file:
      - ./frontend/.env.local

  frontend-dev:
    image: node:20.19-alpine
    profiles:
      - dev
    working_dir: /app
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0 -p 3000"
    ports:
      - "5173:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - chat-service
      - org-service
    env_file:
      - ./frontend/.env.local
  
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9101:9100"
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME}
      - GF_SMTP_SKIP_VERIFY=${GF_SMTP_SKIP_VERIFY}
      - GF_SMTP_STARTTLS_POLICY=${GF_SMTP_STARTTLS_POLICY}
      - GF_SMTP_EHLO_IDENTITY=${GF_SMTP_EHLO_IDENTITY}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
