services:
  auth-service:
    image: trancendance-auth-service:latest
    build:
      context: .
      dockerfile: backend/services/auth_service/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}

  chat-service:
    image: trancendance-chat-service:latest
    build:
      context: .
      dockerfile: backend/services/chat_service/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}

  org-service:
    image: trancendance-org-service:latest
    build:
      context: .
      dockerfile: backend/services/org_service/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}

  notification-service:
    image: trancendance-notification-service:latest
    build:
      context: .
      dockerfile: backend/services/notification_service/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}

  frontend:
    build: ./frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - chat-service
      - org-service
      - notification-service

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9101:9100"
    volumes:
      - /:/host:ro
    command:
      - '--path.rootfs=/host'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
