global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /api/auth-service/metrics
    static_configs:
      - targets: ['auth-service:5001']

  - job_name: 'chat-service'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /api/chat-service/metrics
    static_configs:
      - targets: ['chat-service:5002']

  - job_name: 'org-service'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /api/org-service/metrics
    static_configs:
      - targets: ['org-service:5003']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
