apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: https://prometheus:9090/prometheus
    jsonData:
      tlsSkipVerify: true
    isDefault: true
    editable: true
